[project]
name = "internal-static-files"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.6.5",
    "fastapi[standard]>=0.136.1",
    "markdown-it-py>=4.2.0",
    "psycopg[binary]>=3.3.2",
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.10.1",
    "sqlalchemy>=2.0.44",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
